backend:
  name: github
  repo: fangxinzhen/fangxinzhen.github.io
  branch: main
  auth_scope: repo

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "分类", name: "categories", widget: "list" }
      - { label: "标签", name: "tags", widget: "list" }
      - { label: "内容", name: "body", widget: "markdown" }
